# Quality SimFin

Value-level data quality checks: accounting identities, cross-statement consistency, plausibility.

Tolerance: relative diff > 0.5% (configurable in `irp.quality.rules.violations`).

In [1]:
import pandas as pd
from IPython.display import display
from pandas.io.formats.style_render import ExtFormatter

from irp.quality import REGISTRY, run

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 240)


def _edgar_link(url):
    return f'<a href="{url}" target="_blank">view</a>' if url else ''


_NUM_FMT: ExtFormatter = {
    'LHS_value': '{:,.0f}',
    'RHS_value': '{:,.0f}',
    'diff': '{:,.0f}',
    'rel_diff': '{:.2%}',
    'EDGAR': _edgar_link,
}

SAMPLE = ['AAPL', 'MSFT', 'NVDA', 'GOOGL', 'AMZN', 'META', 'JPM', 'XOM', 'JNJ', 'WMT']

In [2]:
run(['VSAT']).style.format(_NUM_FMT)

## Registered Rules

In [3]:
_rules_df = pd.DataFrame([
    {'Rule': r.name, 'Statement': r.statement, 'LHS': r.lhs, 'RHS': r.rhs}
    for r in REGISTRY
])
display(_rules_df)

                     Rule Statement                                       LHS                                                RHS
0            assets_split   balance                              Total Assets     Total Current Assets + Total Noncurrent Assets
1              liab_split   balance                         Total Liabilities  Total Current Liabilities + Total Noncurrent L...
2       liab_equity_split   balance                Total Liabilities & Equity                   Total Liabilities + Total Equity
3     accounting_equation   balance                              Total Assets                         Total Liabilities & Equity
4            gross_profit    income                              Gross Profit                          Revenue + Cost of Revenue
5        operating_income    income                   Operating Income (Loss)                  Gross Profit + Operating Expenses
6          continuing_ops    income  Income (Loss) from Continuing Operations  Pretax Income (Loss) + Income Tax (Expense) Be...
7        net_income_split    income                                Net Income  Income (Loss) from Continuing Operations + Net...
8              cash_chain  cashflow                        Net Change in Cash                                    CFO + CFI + CFF
9   ni_income_vs_cashflow     cross                       Net Income (income)                Net Income/Starting Line (cashflow)
10  da_income_vs_cashflow     cross      |Depreciation & Amortization| income             |Depreciation & Amortization| cashflow
11     shares_basic_cross     cross                     Shares (Basic) income                             Shares (Basic) balance

## Annual

In [4]:
findings_A = run(SAMPLE, 'A')
print(f'Total findings: {len(findings_A)}')
display(findings_A.drop(columns=['CIK'], errors='ignore').style.format(_NUM_FMT))

Total findings: 37

## Quarterly

In [5]:
findings_Q = run(SAMPLE, 'Q')
print(f'Total findings: {len(findings_Q)}')
display(findings_Q.drop(columns=['CIK'], errors='ignore').style.format(_NUM_FMT))

Total findings: 147

## Findings by Rule

In [6]:
if len(findings_A):
    display(findings_A.groupby(['Rule', 'Ticker']).size().unstack(fill_value=0))
else:
    print('No annual findings.')

Ticker                 AMZN  JNJ  META  MSFT  WMT  XOM
Rule
cash_chain                5    4     4     5    5    4
ni_income_vs_cashflow     0    0     0     0    5    5

## Findings by Ticker

In [7]:
if len(findings_A):
    display(findings_A.groupby('Ticker').size().sort_values(ascending=False))
else:
    print('No annual findings.')

Ticker
WMT     10
XOM      9
MSFT     5
AMZN     5
JNJ      4
META     4
dtype: int64

## Detail per Rule

In [8]:
for _rule_name, _group in findings_A.groupby('Rule'):
    print(f'=== {_rule_name} ({len(_group)} violations) ===')
    display(_group.drop(columns=['Rule', 'Statement', 'CIK'], errors='ignore').style.format(_NUM_FMT))
    print()

=== cash_chain (27 violations) ===

=== ni_income_vs_cashflow (10 violations) ===