# Summary Fundamental Data

In [1]:
import pandas as pd
from IPython.display import display

from irp.data import fundamentals

In [2]:
_META = {
    'Ticker',
    'SrcId',
    'Src',
    'Currency',
    'Fiscal Year',
    'Fiscal Period',
    'Report Date',
    'Publish Date',
    'Restated Date',
    'Market',
    'Period',
}


def summarize(df: pd.DataFrame, name: str) -> None:
    tickers = sorted(df['Ticker'].unique())
    items = [c for c in df.columns if c not in _META]
    print(f'=== {name} ===')
    print(f'Rows: {len(df):,}  |  Tickers: {len(tickers)}')
    print(
        f'Fiscal Year : {int(df["Fiscal Year"].min())} – {int(df["Fiscal Year"].max())}'
    )
    print(
        f'Report Date : {df["Report Date"].min().date()} – {df["Report Date"].max().date()}'
    )
    print(f'\nTickers ({len(tickers)}): {", ".join(tickers)}')
    print(f'\nStatement items ({len(items)}):')
    for col in items:
        n = df[col].notna().sum()
        print(f'  {col:<50s}  {n:>6,}  ({100 * n / len(df):.0f}%)')

## Statement Tables

### Income

In [3]:
income_A = fundamentals(statement='income', variant='A')
income_Q = fundamentals(statement='income', variant='Q')
income = pd.concat([income_A, income_Q])

In [4]:
summarize(income, 'Income Statement')

=== Income Statement ===
Rows: 67,757  |  Tickers: 4692
Fiscal Year : 2020 – 2025
Report Date : 2020-06-30 – 2025-04-30


### Balance

In [5]:
balance_A = fundamentals(statement='balance', variant='A')
balance_Q = fundamentals(statement='balance', variant='Q')
balance = pd.concat([balance_A, balance_Q])

In [6]:
summarize(balance, 'Balance Sheet')

=== Balance Sheet ===
Rows: 67,752  |  Tickers: 4694
Fiscal Year : 2020 – 2025
Report Date : 2020-06-30 – 2025-04-30


### Cachflow

In [7]:
cashflow_A = fundamentals(statement='cashflow', variant='A')
cashflow_Q = fundamentals(statement='cashflow', variant='Q')
cashflow = pd.concat([cashflow_A, cashflow_Q])

In [8]:
summarize(cashflow, 'Cash Flow Statement')

=== Cash Flow Statement ===
Rows: 67,747  |  Tickers: 4693
Fiscal Year : 2020 – 2025
Report Date : 2020-06-30 – 2025-04-30


## Problem Tickers

### Missing by Period

In [15]:
# _stmt_map = {'income': income_A, 'balance': balance_A, 'cashflow': cashflow_A}
# _stmt_map = {'income': income_Q, 'balance': balance_Q, 'cashflow': cashflow_Q}
_stmt_map = {'income': income, 'balance': balance, 'cashflow': cashflow}

In [16]:
def _fp(df):
    # annual Fiscal Period varies by statement ('FY' for income/cashflow, 'Q4' for balance)
    # normalize all annual rows to 'FY' so the pivot key is consistent across statements
    fp = df['Period'].map({'A': 'FY'}).fillna(df['Fiscal Period'])
    return df[['Ticker', 'Fiscal Year']].assign(**{'Fiscal Period': fp})


all_combos = pd.concat([
    _fp(df).assign(stmt=name)
    for name, df in _stmt_map.items()
]).drop_duplicates()

pivot = (
    all_combos.assign(present=1)
    .pivot_table(
        index=['Ticker', 'Fiscal Year', 'Fiscal Period'],
        columns='stmt',
        values='present',
    )
    .fillna(0)
    .reset_index()
)
pivot.columns.name = None

stmts = list(_stmt_map.keys())
problems = pivot[pivot[stmts].eq(0).any(axis=1)].copy()
problems = problems.sort_values(['Ticker', 'Fiscal Year', 'Fiscal Period']).reset_index(drop=True)
for col in stmts:
    problems[col] = problems[col].map({1: '✓', 0: '✗'})

print(f'Problem periods: {len(problems):,}  |  Tickers affected: {problems["Ticker"].nunique()}')
display(problems)

Problem periods: 34  |  Tickers affected: 20

   Ticker  Fiscal Year Fiscal Period balance cashflow income
0    ADBE         2020            Q2       ✓        ✓      ✗
1      AE         2020            Q2       ✗        ✗      ✓
2    AFRM         2021            FY       ✗        ✓      ✓
3    AFRM         2021            Q3       ✓        ✗      ✓
4    AFRM         2021            Q4       ✗        ✓      ✓
5    AFRM         2022            Q1       ✗        ✓      ✓
6    AITX         2020            FY       ✓        ✗      ✗
7    APOG         2020            Q1       ✓        ✗      ✗
8     AZO         2025            Q3       ✓        ✗      ✓
9    BBBY         2020            Q1       ✓        ✗      ✗
10   GBTG         2020            FY       ✓        ✗      ✓
11   GTIM         2020            FY       ✓        ✗      ✓
12    MOS         2020            Q4       ✓        ✗      ✗
13    NEP         2020            Q2       ✗        ✗      ✓
14    NEP         2020            Q3       ✗        ✗      ✓
15   PRGO         2020            Q2       ✗        ✗      ✓
16   PRGO         2020            Q3       ✗        ✗      ✓
17   PRGO         2020            Q4       ✓        ✓      ✗
18    PTE         2020            Q2       ✗        ✗      ✓
19    RAD         2020            Q1       ✓        ✗      ✗
20   SANP         2025            Q3       ✗        ✓      ✗
21    TDG         2020            FY       ✗        ✓      ✓
22    TDG         2020            Q1       ✓        ✗      ✗
23    TDG         2020            Q2       ✓        ✓      ✗
24    TDG         2020            Q3       ✓        ✗      ✓
25    TDG         2020            Q4       ✗        ✓      ✗
26    TDG         2021            Q1       ✗        ✓      ✓
27    TDG         2021            Q2       ✓        ✗      ✓
28    TDW         2020            Q3       ✗        ✓      ✓
29    TDW         2020            Q4       ✓        ✗      ✓
30   TMRC         2020            FY       ✓        ✗      ✗
31     UA         2022            Q1       ✗        ✓      ✓
32   VXRT         2020            Q2       ✗        ✗      ✓
33   VXRT         2020            Q3       ✗        ✗      ✓

In [17]:
problems[problems['Ticker']=='AITX']

  Ticker  Fiscal Year Fiscal Period balance cashflow income
6   AITX         2020            FY       ✓        ✗      ✗

In [21]:
ticker = 'AITX'
income.loc[
    income['Ticker'] == ticker, ['Ticker', 'Period', 'Fiscal Year', 'Fiscal Period']
].sort_values(['Period', 'Fiscal Year'])

Empty DataFrame
Columns: [Ticker, Period, Fiscal Year, Fiscal Period]
Index: []

In [13]:
ticker = 'ZYXI'
y=2021

mask = (income['Ticker']== ticker) & (income['Fiscal Year']==y)
display(income[mask])

mask = (balance['Ticker']== ticker) & (balance['Fiscal Year']==y)
display(balance[mask])

mask = (cashflow['Ticker']== ticker) & (cashflow['Fiscal Year']==y)
display(cashflow[mask])

,Ticker,SrcId,Src,Currency,Fiscal Year,Fiscal Period,Report Date,Publish Date,Restated Date,Shares (Basic),...,"Pretax Income (Loss), Adj.",Abnormal Gains (Losses),Pretax Income (Loss),"Income Tax (Expense) Benefit, Net",Income (Loss) from Continuing Operations,Net Extraordinary Gains (Losses),Net Income,Net Income (Common),Market,Period
17117,ZYXI,171401,simfin,USD,2021,FY,2021-12-31,2022-03-22,2025-03-11,37255900,...,-6078000,-2874000,-8952000,2214000,-6738000,<NA>,-6738000,-6738000,us,A
50631,ZYXI,171401,simfin,USD,2021,Q1,2021-03-31,2021-04-29,2022-04-28,34837000,...,-1090000,<NA>,-1090000,384000,-706000,<NA>,-706000,-706000,us,Q
50632,ZYXI,171401,simfin,USD,2021,Q4,2021-12-31,2022-03-22,2022-10-27,44608600,...,-16786000,-2874000,-19660000,4713000,-14947000,<NA>,-14947000,-14947000,us,Q
50633,ZYXI,171401,simfin,USD,2021,Q2,2021-06-30,2021-07-29,2022-07-28,34810000,...,3770000,<NA>,3770000,-962000,2808000,<NA>,2808000,2808000,us,Q
50634,ZYXI,171401,simfin,USD,2021,Q3,2021-09-30,2021-11-02,2022-10-27,34768000,...,8028000,<NA>,8028000,-1921000,6107000,<NA>,6107000,6107000,us,Q

,Ticker,SrcId,Src,Currency,Fiscal Year,Fiscal Period,Report Date,Publish Date,Restated Date,Shares (Basic),...,Long Term Debt,Total Noncurrent Liabilities,Total Liabilities,Share Capital & Additional Paid-In Capital,Treasury Stock,Retained Earnings,Total Equity,Total Liabilities & Equity,Market,Period
17117,ZYXI,171401,simfin,USD,2021,Q4,2021-12-31,2022-03-22,2023-03-14,37255900,...,10605000,36478000,59349000,80438000,-6513000,<NA>,73925000,133274000,us,A
50626,ZYXI,171401,simfin,USD,2021,Q3,2021-09-30,2021-11-02,2021-11-02,34768000,...,<NA>,17048000,27340000,38257000,-6513000,31639000,63383000,90723000,us,Q
50627,ZYXI,171401,simfin,USD,2021,Q1,2021-03-31,2021-04-29,2021-04-29,34837000,...,<NA>,4768000,14083000,37350000,-3921000,22724000,56153000,70236000,us,Q
50628,ZYXI,171401,simfin,USD,2021,Q2,2021-06-30,2021-07-29,2021-07-29,34810000,...,<NA>,17507000,26398000,37734000,-5966000,25532000,57300000,83698000,us,Q
50629,ZYXI,171401,simfin,USD,2021,Q4,2021-12-31,2022-03-22,2023-03-14,44608600,...,10605000,36478000,59349000,80438000,-6513000,<NA>,73925000,133274000,us,Q

,Ticker,SrcId,Src,Currency,Fiscal Year,Fiscal Period,Report Date,Publish Date,Restated Date,Shares (Basic),...,Net Change in Long Term Investment,Net Cash from Acquisitions & Divestitures,Net Cash from Investing Activities,Dividends Paid,Cash from (Repayment of) Debt,Cash from (Repurchase of) Equity,Net Cash from Financing Activities,Net Change in Cash,Market,Period
17115,ZYXI,171401,simfin,USD,2021,FY,2021-12-31,2022-03-22,2023-03-14,37255900,...,<NA>,-15997000,-16606000,-1000,15855000,-2506000,13096000,3439000,us,A
50623,ZYXI,171401,simfin,USD,2021,Q3,2021-09-30,2021-11-02,2022-07-28,34768000,...,<NA>,<NA>,-66000,<NA>,-29000,-508000,-585000,3038000,us,Q
50624,ZYXI,171401,simfin,USD,2021,Q1,2021-03-31,2021-04-29,2022-04-28,34837000,...,<NA>,<NA>,-299000,<NA>,-23000,-48000,-130000,-5734000,us,Q
50625,ZYXI,171401,simfin,USD,2021,Q4,2021-12-31,2022-03-22,2022-10-27,44608600,...,<NA>,-15997000,-16186000,-1000,15928000,34000,15892000,7244000,us,Q
50626,ZYXI,171401,simfin,USD,2021,Q2,2021-06-30,2021-07-29,2022-04-28,34810000,...,<NA>,<NA>,-55000,<NA>,-21000,-1984000,-2081000,-1109000,us,Q

In [14]:
fundamentals('ZYXI', 'balance')

,Ticker,SrcId,Src,Currency,Fiscal Year,Fiscal Period,Report Date,Publish Date,Restated Date,Shares (Basic),...,Long Term Debt,Total Noncurrent Liabilities,Total Liabilities,Share Capital & Additional Paid-In Capital,Treasury Stock,Retained Earnings,Total Equity,Total Liabilities & Equity,Market,Period
0,ZYXI,171401,simfin,USD,2024,Q4,2024-12-31,2025-03-11,2025-11-17,31941000,...,58567000,69507000,86371000,93120000,-87186000,29774000,35708000,122079000,us,A
1,ZYXI,171401,simfin,USD,2023,Q4,2023-12-31,2024-03-12,2025-03-11,35555000,...,57605000,72243000,90775000,90911000,-71562000,26780000,46129000,136904000,us,A
2,ZYXI,171401,simfin,USD,2022,Q4,2022-12-31,2023-03-14,2024-03-12,38467000,...,5293000,29022000,50108000,82470000,-33160000,17048000,66358000,116466000,us,A
3,ZYXI,171401,simfin,USD,2021,Q4,2021-12-31,2022-03-22,2023-03-14,37255900,...,10605000,36478000,59349000,80438000,-6513000,<NA>,73925000,133274000,us,A
4,ZYXI,171401,simfin,USD,2020,Q4,2020-12-31,2021-02-25,2022-03-22,33869000,...,<NA>,5203000,15320000,37235000,-3846000,23430000,56855000,72175000,us,A